---
# tasks file for ec2-1
- name: Add the user 'docker', appending the group 'users' to the user's groups
  user:
    name: docker
    groups: users
    append: yes
  become: yes

- name: Check If Python and Docker Are Installed
  apt:
    name:
       - python3-pip
       - docker.io
    state: present
    update_cache: yes
  become: yes

- name: make sure docker-py installed
  become: yes
  pip:
    name: docker-py

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: started

- name: Clone Git Repository
  git:
    repo: https://github.com/segevb/weather.git
    dest: /home/ubuntu/weather

- name: Log into DockerHub
  become: yes
  docker_login:
    username: "{{ dockerhub_user }}"
    password: "{{ dockerhub_pass }}"
    api_version: auto

- name: Build an image and push to docker hub
  become: yes
  docker_image:
    build:
      path: /home/ubuntu/weather
    name: weather_app:0.5
    repository: segevb/weather_app
    push: yes
    source: build

