---
# tasks file for ec2-2
- name: Check If Python and Docker are installed
  apt:
    name:
      - python3-pip
      - docker.io
    state: present
    update_cache: yes
  become: yes

- name: make sure docker-py is installed
  become: yes
  pip:
    name: docker-py

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: started

- name: pull a Docker Image
  become: yes
  docker_image:
    name: segevb/weather_app:v0.5




